spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
    schema: classpath*:schema.sql
  etl:
    datasource:
      url: jdbc:h2:mem:etl
      driver-class-name: org.h2.Driver
      username: root
      password: 123456
      schema: classpath*:schema.sql
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      springframework:
        jdbc: trace

mybatis:
  configuration:
    map-underscore-to-camel-case: true