spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
    schema: classpath*:schema-test.sql
  etl:
    datasource:
      url: jdbc:h2:mem:etl;MODE=MySQL
      driver-class-name: org.h2.Driver
      username: root
      password: 123456
      schema: classpath*:schema-etl.sql
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      springframework:
        jdbc: trace
    com:
      example:
        mapper: debug

mybatis:
  configuration:
    map-underscore-to-camel-case: true